version: "2"

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
    - durationcheck
    - errorlint
    - errchkjson
    - errname
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocritic
    - gosec
    - makezero
    - mirror
    - misspell
    - modernize
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - reassign
    - recvcheck
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - unconvert
    - unqueryvet
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
